# Generated by Django 4.1.6 on 2023-02-15 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Accounts', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='porpose',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Renter'),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_notif',
            field=models.BooleanField(default=True, verbose_name='Notify me'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('A', 'Admin'), ('C', 'Renter')], default='C', max_length=3, verbose_name='Type (Admin/Renter)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=54, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='Username should be Contained Alphabitical', regex='^[A-Za-z]+$')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=54, validators=[django.core.validators.RegexValidator(code='invalid_last_name', message='Username should be Contained Alphabitical', regex='^[a-z A-Z]*$')], verbose_name='Last Name'),
        ),
    ]
